### ISSUE TITLE
Can't find a way to add a custom field to the section

### ISSUE THREAD

**Issue by kty0mka** [nanego/redmine_custom_fields_sections#3]
Custom Fields sections tab in admin settings only lets me create or rename section.
I can't find a way to add a custom field to the section in CFS tab nor in a custom field settings.

**Comment by ashrafalzyoud** [comment]
like me

**Comment by nanego** [comment]
Hello
This new plugin only groups project's custom-fields for now.
If you edit a project custom field, you should see, at the bottom, a select box which allows you to choose a section.
We may add Issue Custom Field support later eventually.
